# Periphery dead code detection — local development use only.
# Not integrated in CI. Run manually: periphery scan
project: ElementX.xcodeproj
schemes:
- ElementX
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
targets:
- ElementX
- NSE
- ShareExtension
- UnitTests
- PreviewTests
- UITests
- IntegrationTests
report_exclude:
  - ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  - ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
retain_swift_ui_previews: true
