settings:
  APP_DISPLAY_NAME: Element X
  PRODUCTION_APP_NAME: Element
  APP_GROUP_IDENTIFIER: group.im.g
  BASE_BUNDLE_IDENTIFIER: im.g.message
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT
